### ISSUE TITLE
[Potential BUG] Variation seeds should be stored in generated image yaml files

### ISSUE THREAD

**Issue by JoshuaKimsey** [sd-webui/stable-diffusion#167]
I'm gonna put this here as it seems like it's a potential bug, or at least an issue that needs resolving. 

I noticed when using the Variations feature that the seeds and stats for what were used for those images aren't saved in their respective yaml file. This makes it incredibly hard to be able to go back and figure out exactly what the parameters where that were used for that specific image. Given the other output data already stored in those files, it definitely seems like the variations data should be stored there as well.

**Comment by Arkitecc** [comment]
I second this, we definitely need to have this information added in each variations respective .yaml file, its critical for returning to the images later for further editing and development.

**Comment by WilliamRandol** [comment]
Also, any of the toggles that can effect the image (like normalize, gpfgan, esrgan)  should be saved to the .yaml as specific values, instead of just as part of the list of enabled toggles. In case that toggle list were to change, or even change order. 

Maybe it would even make sense to give all the toggles their own values.
